title: WebEZ Walkthroughs
description: Walkthroughs for various WebEZ features and functions.
theme: just-the-docs

url: https://ud-s24-cisc181.github.io/hw8-webez-basics-walkthrough/

markdown: kramdown


callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red